// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC54U2VaMpbgiNGmcaIhvWwOnS157xrojs',
    appId: '1:146541742460:web:65bb6176e2f5e58fbcbcf9',
    messagingSenderId: '146541742460',
    projectId: 'gas-leakage-detection-9391e',
    authDomain: 'gas-leakage-detection-9391e.firebaseapp.com',
    databaseURL: 'https://gas-leakage-detection-9391e-default-rtdb.firebaseio.com',
    storageBucket: 'gas-leakage-detection-9391e.firebasestorage.app',
    measurementId: 'G-QXMSTK50MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5pp3g6a8Hm60BgZZ7kbmy0bizgqv5j4',
    appId: '1:146541742460:android:e1edcfffc1ecbb1dbcbcf9',
    messagingSenderId: '146541742460',
    projectId: 'gas-leakage-detection-9391e',
    databaseURL: 'https://gas-leakage-detection-9391e-default-rtdb.firebaseio.com',
    storageBucket: 'gas-leakage-detection-9391e.firebasestorage.app',
  );
}
